#!/bin/bash
if [ $1 == "0" ]
then
	cn=$2
	username=${cn:3}
	#пример с http get, так же возможно применять WebAPI для Curl запрос с ""-u"
	answer=$(curl http://192.168.0.12:8081/account/billing/$username | grep -c "YES")
	if [ $answer == "1"  ]
	then
		exit 0
	fi
	exit 1
else
	exit 0
fi
